### PR TITLE
12614: XLSForm export: Add default value, repeat count, and media prompt columns

### PR DESCRIPTION
**Pull request by plastichotsprings**
Straightforwardly adds additional columns from NEMO question settings. Notes:

- NEMO allows you to "preload last saved answer as a default" - how is this accomplished in XLSForm? (SEE BELOW) ✅ 
- XLSForm allows you to put in a static value as a repeat count, in NEMO you must reference another question's value. ✅ 
- When uploading media_prompt files, NEMO changes the filename to a string of random numbers (e.g., `675f1bab-7de2-4527-b743-fb204c1ebcf5_media_prompt.png`). We may need to warn users because it may not be trivial to actually locate the files they have previously uploaded in order to transfer them over to the new system. Or, is there a way to locate the original filename? ✅ 
- Media_prompt column is tested and working with audio and image uploads, but i didn't have an .mp4 (only allowed video type) of under 50 MB to test with. ✅

### CODE REVIEW

**Comment by plastichotsprings** [comment]
> ## 🔍 Existing Issues For Review
> 
> Your pull request is modifying functions with the following pre-existing issues:
> 
> 📄 File: **app/models/forms/export.rb**
> Function 	Unhandled Issue
> **`to_xls`** 	[**NoMethodError: undefined method `first' for nil (NoMethodError)**](https://sassafras.sentry.io/issues/6334294216/?referrer=github-open-pr-bot) FormsContro... <br> `Event Count:` **1**
> 
> Did you find this useful? React with a 👍 or 👎

this should be okay since i'm using safe navigation `q.media_prompt.content_type&.split("/")&.first` to get the file type. or is this bad practice..?

**Comment by plastichotsprings** [comment]
"preload last saved answer" would look like this as a default ([docs](https://docs.getodk.org/form-logic/#values-from-the-last-saved-record)): ${last-saved#TextQ1}

**Review by cooperka — CHANGES_REQUESTED** [review]
just needs ::Language settings, but i confirmed it does all work once adding those into the excel file manually

**Comment by cooperka** [comment]
spec is a flapper

**Review by cooperka — APPROVED** [review]
tested and verified in central 🏅
